version: '3'

services:
  pokedexapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      APP_ID: ${APP_ID}
      API_PREFIX: ${API_PREFIX}
      NODE_ENV: ${NODE_ENV}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      DEFAULT_OFFSET: ${DEFAULT_OFFSET}
      PORT: ${PORT}
      MONGO_HOST: ${MONGO_HOST}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db